### ISSUE TITLE
Temperature trigger lags for several hours

### ISSUE THREAD

**Issue by MrXlebNick** [shenxn/ha-dyson#132]
The automation is configured to be triggered when the temperature rises above 24 degrees, and it was triggered several hours after it actually happened.

The integration information:
![image](https://user-images.githubusercontent.com/10089784/165387771-da8ec037-6c8b-4459-8dff-689eb6cf558b.png)

The configuration of the automation:

```
alias: Dyson - Turn on when too hot
description: ''
trigger:
  - platform: device
    device_id: 3c67276f07b37446e07791c0d8b441bb
    domain: climate
    entity_id: climate.pure_hot_cool_link
    type: current_temperature_changed
    above: 24
condition: []
action:
  - device_id: 3c67276f07b37446e07791c0d8b441bb
    domain: fan
    entity_id: fan.pure_hot_cool_link
    type: turn_on
  - device_id: 3c67276f07b37446e07791c0d8b441bb
    domain: climate
    entity_id: climate.pure_hot_cool_link
    type: set_hvac_mode
    hvac_mode: cool
mode: single
```

Temperature graph:
![image](https://user-images.githubusercontent.com/10089784/165387210-96a6cc75-c093-4fc2-b0f8-1e3e28b04c82.png)

Dyson's on/off timeline:
![image](https://user-images.githubusercontent.com/10089784/165387333-8b1a673e-024d-4fe0-ae95-634ac914ecf6.png)

The event that has turned the Dyson on:
![image](https://user-images.githubusercontent.com/10089784/165387495-a6a586a1-49e6-4874-b9d1-0393aa8e0084.png)
Changed variables:
```
this:
  entity_id: automation.new_automation
  state: 'on'
  attributes:
    last_triggered: '2022-04-26T12:37:40.891183+00:00'
    mode: single
    current: 0
    id: '1650976349607'
    friendly_name: Dyson - Turn on when too hot
  last_changed: '2022-04-26T13:32:47.136634+00:00'
  last_updated: '2022-04-26T13:32:47.136634+00:00'
  context:
    id: 517382f678ea857a07bd3319d09cda2e
    parent_id: null
    user_id: null
trigger:
  id: '0'
  idx: '0'
  platform: device
  entity_id: climate.pure_hot_cool_link
  below: null
  above: 24
  from_state:
    entity_id: climate.pure_hot_cool_link
    state: 'off'
    attributes:
      hvac_modes:
        - 'off'
        - cool
        - heat
      min_temp: 1
      max_temp: 37
      fan_modes:
        - focus
        - diffuse
      current_temperature: 21.8
      temperature: 26
      current_humidity: 25
      fan_mode: focus
      hvac_action: 'off'
      friendly_name: Pure Hot+Cool Link
      supported_features: 9
    last_changed: '2022-04-26T13:20:23.545745+00:00'
    last_updated: '2022-04-26T13:21:08.048654+00:00'
    context:
      id: 673cefc1ec85229d2a2df892b9c1bfc9
      parent_id: null
      user_id: null
  to_state:
    entity_id: climate.pure_hot_cool_link
    state: 'off'
    attributes:
      hvac_modes:
        - 'off'
        - cool
        - heat
      min_temp: 1
      max_temp: 37
      fan_modes:
        - focus
        - diffuse
      current_temperature: 26.1
      temperature: 26
      current_humidity: 24
      fan_mode: focus
      hvac_action: 'off'
      friendly_name: Pure Hot+Cool Link
      supported_features: 9
    last_changed: '2022-04-26T13:20:23.545745+00:00'
    last_updated: '2022-04-26T17:07:42.048862+00:00'
    context:
      id: f8657a6d59f8214044eb1bc680637cc9
      parent_id: null
      user_id: null
  for: null
  description: numeric state of climate.pure_hot_cool_link
```
