### ISSUE TITLE
Can't set auto mode through service fan.set_preset_mode

### ISSUE THREAD

**Issue by Phontana** [shenxn/ha-dyson#36]
I'm unable to set the auto mode through the service `fan.set_preset_mode`. The preset_modes array of the fan is empty:

```
preset_modes: 
```

When calling the service like this:

```
service: fan.set_preset_mode
data:
  entity_id: fan.pure_cool_link
  preset_mode: auto

```

I get the following error (because the array is empty):

```
The preset_mode auto is not a valid preset_mode: []
```

I can set the auto mode by toggling the switch `switch.pure_cool_link_auto_mode` but it would be nice if the fan supported the preset_modes as well.
