### ISSUE TITLE
Pure Hot Cool Link Device Automations fail to detect current mode

### ISSUE THREAD

**Issue by kidhasmoxy** [shenxn/ha-dyson#43]
Using Device Conditions in Automations or Scripts fail to detect the current mode of the Dyson device. As a result, the following automation step produces no action, even though the climate device shows a "heat" state and the physical device is heating the room. 

```
choose:
  - conditions:
      - condition: device
        device_id: 4de31c580c0b72b61b008d44c39fd1
        domain: climate
        entity_id: climate.attic_dyson_air
        type: is_hvac_mode
        hvac_mode: heat
    sequence:
      - service: climate.set_temperature
        data:
          temperature: 60
        target:
          entity_id: climate.dyson_air
      - delay:
          hours: 1
          minutes: 0
          seconds: 0
          milliseconds: 0
      - device_id: 4de31c580c0b72b61b008d44c39fd1
        domain: fan
        entity_id: fan.attic_dyson_air
        type: turn_off
  - conditions:
      - condition: device
        device_id: 4de31c580c0b72b61b008d44c39fd104
        domain: climate
        entity_id: climate.attic_dyson_air
        type: is_hvac_mode
        hvac_mode: cool
    sequence:
      - device_id: 4de31c580c0b72b61b008d44c39fd1
        domain: fan
        entity_id: fan.attic_dyson_air
        type: turn_off
default: []
```
