### ISSUE TITLE
Issue setting fan attributes through automation: Unable to find service

### ISSUE THREAD

**Issue by lcombelet** [shenxn/ha-dyson#47]
Please help me out fixing the following.  I have configured my Dyson fan (TP04) using the Local setup.

The Dyson entity seems to be working correctly, I can use the switches (like auto mode, night mode, front airflow switch, etc.) in my dashboards (ignore speed control, that one isn't working):
![image](https://user-images.githubusercontent.com/35108854/118372307-4a943d80-b5b1-11eb-9089-8ddc42dca3a4.png)

State screenshot from dev-tools:
![dyson_01](https://user-images.githubusercontent.com/35108854/118371897-f5efc300-b5ae-11eb-9b55-7735155f0167.PNG)

Interestingly enough, it seems like my fan is not recognizing the dyson speeds, but is using the HA default LOW, MEDIUM, HIGH. Not sure if I did something wrong during setup, I have no clue how to get rid of this..

My issue is that I am getting errors when trying to set any attribute _through an automation_. I am struggling to get working:
- Speed
- Oscillation (true/false)
- Angle (low and high)
- Front airflow (using the switch on a dashboard works, but not when calling dyson.set_flow_direction_front in an automation..)
- etc.

The automation that I am trying to run should turn on my fan using a number of parameters:

```
- id: bedroom_cooling
  alias: Bedroom Cooling
  description: Cool the bedroom in the evening
  trigger:
  - platform: numeric_state
    entity_id: sensor.dyson_temperature
    above: '22'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.lights_living
      state: 'off'
    - condition: state
      entity_id: input_boolean.not_home_enabled
      state: 'off'
  action:
  - service: dyson.set_speed
    data:
      speed: 4
      entity_id: fan.dyson
  - service: dyson.set_flow_direction_front
    data:
      entity_id: fan.dyson
      flow_direction_front: true
  - service: dyson.set_angle
    data:
      angle_low: '90'
      angle_high: '135'
      entity_id: fan.dyson
  - service: fan.oscillate
    data:
      oscillating: true
      entity_id: fan.dyson
  mode: restart
```

The error that I am getting from HA Trace is: 'Unable to find service dyson.set_speed':
![image](https://user-images.githubusercontent.com/35108854/118372043-bd041e00-b5af-11eb-870d-b81338390fda.png)

I must be doing something wrong here, but I have been trying for weeks and I am probably overlooking something stupid here...

Can you please support me in figuring out what's happening because I am going crazy here, hehe.
Thanks for the great integration in any case, after TFA messed up my fan setup, I am happily using your solution.
