### ISSUE TITLE
Dyson pure Hot + Cool link - Missing switch ?

### ISSUE THREAD

**Issue by Nsbx** [shenxn/ha-dyson#54]
Hi,
I installed your integration after seeing the official integration doesn't work.
Everthing works perfectly but i have one question.
Is this normal there is no switch for "oscillating" attributes ?
Currently, i created a custom button that call the service "fan.oscillate" and it work. But with this i can't have all switch in "glance" card and for my current "design" this is problematic.
Do you know if you able to add one more switch for this function ? (i doesn't know python very much so i'm sorry, otherwise i would have made the edit)
Thank for advance

**Comment by shenxn** [comment]
Click on the fan entity and the oscillation switch is on the pop up card. If you really want a switch entity, use a template switch.

**Comment by nodinosaur** [comment]
Hi,
I read this issue as I would find an oscillation button useful.

I can see the switch on the card:
<img width="410" alt="fan" src="https://user-images.githubusercontent.com/2144571/179992986-6599d5fc-f4cf-43c3-8cce-03014055b158.png">

EDIT: my working code sample is further down in this thread

Thanks

**Comment by Nsbx** [comment]
Hi, I have done it like this

```
- type: custom:button-card
  icon: hass:autorenew
  name: Oscillate
  show_state: false
  state_display: >
    [[[ return 'Value : '+states['fan.dyson_link'].attributes.oscillating ]]]
  state:
    - color: var(--paper-item-icon-active-color)
      operator: template
      value: >
        [[[ return states['fan.dyson_link'].attributes.oscillating==true ]]]
    - color: var(--paper-item-icon-color)
      operator: template
      value: >
        [[[ return !states['fan.dyson_link'].attributes.oscillating==true ]]]
  tap_action:
    action: call-service
    service: fan.oscillate
    service_data:
      entity_id: fan.dyson_link
      oscillating: >
        [[[ return !states['fan.dyson_link'].attributes.oscillating ]]]
```

**Comment by nodinosaur** [comment]
Thanks for the tip, I never knew of `fan.oscillate`

my final code works:


The Template Switch:
```
- platform: template
  switches:
    fan_oscillation:
      friendly_name: "Fan oscillation"
      value_template: "{{ is_state_attr('fan.pure_hot_cool_link','oscillating', true) }}"
      turn_on:
        service: fan.oscillate
        target: 
          entity_id: fan.pure_hot_cool_link
        data:
          oscillating: true
      turn_off:
        service: fan.oscillate
        target: 
          entity_id: fan.pure_hot_cool_link
        data:
          oscillating: false
      icon_template: >-
        {% if state_attr('fan.pure_hot_cool_link','oscillating') %}
          hass:swap-horizontal-bold
        {% else %}
          hass:swap-vertical-bold
        {% endif %} 
```

and call the switch:
```
type: grid
columns: 1
square: false
cards:
  - type: grid
    columns: 1
    square: true
    cards:
      - type: thermostat
        entity: climate.pure_hot_cool_link
  - type: grid
    columns: 1
    square: false
    cards:
      - type: entities
        entities:
          - type: custom:slider-entity-row
            entity: fan.pure_hot_cool_link
            show_name: false
  - square: false
    columns: 3
    type: grid
    cards:
      - type: button
        show_icon: true
        show_name: true
        entity: fan.pure_hot_cool_link
        name: Office Fan
      - type: button
        show_name: true
        show_icon: true
        entity: switch.fan_oscillation
        name: Oscillation
      - show_name: true
        show_icon: true
        type: button
        entity: switch.pure_hot_cool_link_focus_mode
        name: Focus Mode
```
