### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by dsumin** [shenxn/ha-dyson#6]
I'm trying to set up integration.

After getting credentials (1kMi......kg==) I'm getting "Failed to connect error", however in the logs there is 
`2021-03-04 10:29:12 INFO (MainThread) [libdyson.dyson_device] Connected to device PT4-EU-JK*` line.

I'm not sure how to trouble shoot this issue.

**Comment by eiddor** [comment]
I know there's some stuff going on with auth and that sometimes you have to open the mobile app, logout, login, and then restart HA again.

I'm still trying to figure out how to get my credentials.

**Comment by shenxn** [comment]
First try restart your device. If that does not work, enable debug log by adding the following lines into your `configuration.yaml` to see if you can get anything useful.
```
logger:
  default: info
  logs:
    libdyson: debug
    custom_components.dyson_local: debug
    custom_components.dyson_cloud: debug
```
