### ISSUE TITLE
Auto mode failing in scenes

### ISSUE THREAD

**Issue by BazaJayGee66** [shenxn/ha-dyson#91]
I'm having issues trying to activate a scene when the preset mode is Auto, using HA 2021.12.9 and ha-dyson v0.16.2

Scene is created in the UI, by adding the Dyson fan device and selecting the preset mode as Auto in the fan entity.

When attempting to run the scene when the fan is set to anything other than Auto, the bellow error is shown:

<img width="624" alt="Screen Shot 2022-01-16 at 10 00 01 pm" src="https://user-images.githubusercontent.com/19566498/149657351-36bff663-9998-4c9b-b159-807881d52016.png">

Having a look at the `scenes.yaml` I can see it gets created without any value for percentage

```yaml
- id: '1642327774528'
  name: Auto Air Purify
  entities:
    fan.dyson_lounge_room_fan:
      speed_list:
      - 'off'
      - low
      - medium
      - high
      - Auto
      preset_modes:
      - Auto
      direction: forward
      oscillating: true
      speed:
      percentage:
      percentage_step: 10
      preset_mode: Auto
      angle_low: 135
      angle_high: 225
      friendly_name: Dyson Lounge Room Fan
      supported_features: 15
      state: 'on'
```
